name: BPNightVision
main: com.blueprintmc.nightvision.BPNightVision
author: jstnf
version: 1.0.0

commands:
  nv:
    description: Command to toggle night vision on and off.
    permission: bpnightvision.nv
    aliases: [nightvision, bpnv]

permissions:
  bpnightvision.nv:
    description: Allow players to toggle night vision on and off.
    default: false
  bpnightvision.list:
    description: List all players with night vision on.
    default: false